

name: Build and deploy ASP.Net Core app to Render.com - Kanji-teacher-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Trigger Render deploy
        run: |
          curl -X POST "${{secrets.RENDER_DEPLOY_URL}}"
